[build-system]
requires = ["setuptools>=80.9.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sentiment-package"
version = "0.1.1"
description = "Package to analyse EV swap related issues"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.1",
    "pytest>=8.4.1",
    "setuptools>=80.9.0",
]

[tool.setuptools.packages.find]
where = ["src"]
